/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_ndk_NDKExam */

#ifndef _Included_org_example_ndk_NDKExam
#define _Included_org_example_ndk_NDKExam
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_ndk_NDKExam
 * Method:    getScore
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_example_ndk_NDKExam_getScore
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_example_ndk_NDKExam
 * Method:    startGame
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_example_ndk_NDKExam_startGame
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_example_ndk_NDKExam
 * Method:    finishGame
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_example_ndk_NDKExam_finishGame
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_example_ndk_NDKExam
 * Method:    driveOpen
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_example_ndk_NDKExam_driveOpen
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
